### ISSUE TITLE
Should allow for renderToString rather than using view engine

### ISSUE THREAD

**Issue by jaraquistain** [jhollingworth/marty-express#12]
As far as I can tell the middleware forces the user to use express' template rendering engine, rather than giving the choice between using the template engine or using React.renderToString. As a consequence, it forces an otherwise unnecessary dependency on some templating framework and prevents the use of things like react-side-effect to popuate dynamic `<head>` content.

Are there any future plans to support rendering the entire HTML response with react rather than the usual Express renderers?

**Comment by jaraquistain** [comment]
Closing this since development is dead

**Comment by goldensunliu** [comment]
@jaraquistain doesn't mean you can't jump on it :-P. 
![](https://media3.giphy.com/media/aptJIZbitjf2g/200.gif)
